import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'example'}],
  hardwareSidebar:[{type: 'autogenerated', dirName: 'hardware'}],
  softwareSidebar:[{type: 'autogenerated', dirName: 'software'}],

  specSidebar:[{type: 'autogenerated', dirName: 'spec'}],
  // specSidebar: [
  //   'spec/intro',
  //   'spec/get_started',
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     items: [
  //       'spec/guides/custom_extension',
  //       'spec/guides/rules',
  //     ],
  //   },
  //   {
  //     type:'category',
  //     label:'The ISA Specification',
  //     link: {type: 'doc', id: 'spec/intro'},
  //     items:[
  //       {
  //         type:"link",
  //         label:"ISA Volume 1: Priv",
  //         href:"/isa",
  //       },
  //       {
  //         type:"link",
  //         label:"ISA Volume 2: Un-Priv",
  //         href:"/isa",
  //       },

  //     ],
  //   },
  //   {
  //     type:'category',
  //     label:'Profiles',
  //     link: {type: 'doc', id: 'spec/profiles'},
  //     items:[
  //       {
  //         type:"link",
  //         label:"RVA23",
  //         href:"#todo",
  //       },
  //       {
  //         type:"link",
  //         label:"RVB23",
  //         href:"#TODO",
  //       },
  //       {
  //         type:"link",
  //         label:"Archived Profiles",
  //         href:"#todo",
  //       },

  //     ],
  //   },
  //   {
  //     type:'autogenerated', dirName: 'spec/non-isa'
  //   },
  //   // {
  //   //   type:'category',
  //   //   label:'Non-ISA Specifications',
  //   //   link: {type: 'doc', id: 'spec/non-isa'},
  //   //   items:[
  //   //     {
  //   //       type:'autogenerated', dirName: 'spec/non-isa'
  //   //     }
  //   //   ],
  //   // },
  // ],

};

export default sidebars;
